<?php
/* ==========================================================================
   CMS CONFIG
   ==========================================================================
   Everything the admin panel needs to find its database and its folders.

   THIS FILE HOLDS NO SECRETS and is committed. The defaults below run on
   SQLite, which needs no server, no user and no password — copy the site to a
   host, load /admin/, and it works.

   To point at MySQL instead, do NOT edit this file: create
   includes/config.local.php beside it and return only the keys you are
   changing. That file is in .gitignore, so a database password put there is
   never committed, and a `git pull` never overwrites it.

       <?php
       return array(
           'db' => array(
               'driver' => 'mysql',
               'host'   => 'localhost',
               'name'   => 'sachdeva_cms',
               'user'   => 'sachdeva',
               'pass'   => '…',
           )
       );

   The merge is one level deep on purpose: 'db' is replaced wholesale, so a
   partial db block would drop the keys it leaves out. Give the whole block.
   ========================================================================== */

$config = array(

    /* ---- database ------------------------------------------------------
       driver 'sqlite' keeps the whole database in one file under data/.
       Nothing else is read for sqlite; the mysql keys are ignored.        */
    'db' => array(
        'driver' => 'sqlite',
        'file'   => dirname(__DIR__) . '/data/content.sqlite',

        /* only read when driver is 'mysql' */
        'host'    => 'localhost',
        'port'    => 3306,
        'name'    => 'sachdeva_cms',
        'user'    => 'root',
        'pass'    => '',
        'charset' => 'utf8mb4',
    ),

    /* ---- where uploaded pictures land ----------------------------------
       Paths are relative to the site root so the same string works as a
       filesystem path and as the src= a page is served with.              */
    'upload_dir'  => 'uploads',
    'max_upload'  => 4 * 1024 * 1024,        /* 4 MB per image */
    'image_types' => array('jpg', 'jpeg', 'png', 'webp', 'gif'),

    /* ---- the pages the panel publishes into -----------------------------
       block name  =>  file that carries the matching SG-CMS markers.
       A page listed here that has no markers is skipped with a warning
       rather than being rewritten.                                        */
    'targets' => array(
        'news'         => 'news.html',
        'gallery'      => 'gallery.html',
        'testimonials' => 'about_us.html',
    ),

    /* ---- session / login ------------------------------------------------ */
    'session_name'    => 'SGADMIN',
    'session_idle'    => 2 * 60 * 60,   /* signed out after 2h of no activity */
    'login_max_tries' => 6,             /* per IP … */
    'login_window'    => 15 * 60,       /* … within this many seconds */

    /* ---- shown in the panel chrome -------------------------------------- */
    'site_name' => 'Sachdeva Group of Industries',
    'site_url'  => '',   /* leave empty to detect it from the request */
);

/* local overrides — see the note at the top */
$localFile = __DIR__ . '/config.local.php';
if (is_file($localFile)) {
    $local = require $localFile;
    if (is_array($local)) {
        $config = array_replace($config, $local);
    }
}

return $config;
